# Generated by Django 4.1.5 on 2023-01-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_checkout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
