# Generated by Django 4.1.5 on 2023-02-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0004_alter_checkout_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='profile',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders', to='profiles.profile'),
        ),
    ]
