# Generated by Django 4.1.5 on 2023-02-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
