# Generated by Django 4.1.5 on 2023-02-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('conf_number', models.CharField(
                    editable=False, max_length=12)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
