# Generated by Django 4.1.5 on 2023-02-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
