# Generated by Django 4.1.5 on 2023-02-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
