# Generated by Django 4.1.5 on 2023-02-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_newsletter_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='conf_number',
        ),
    ]
