# Generated by Django 4.1.5 on 2023-01-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='image_url',
        ),
    ]
