# Generated by Django 4.1.5 on 2023-02-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_remove_cake_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='sku',
        ),
        migrations.AddField(
            model_name='cake',
            name='ingredients',
            field=models.CharField(blank=True, max_length=245, null=True),
        ),
    ]
